<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="MAIN" Id="{06c787c3-cfd1-4301-ab7e-6520ebb35bc3}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[prg_jafunctie();
prg_TweeSignalen();
prg_Reactorvat();
prg_Opslagvat();
PRG_OpslagFoutDetectie();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="6" Count="3" />
    </LineIds>
  </POU>
</TcPlcObject>