<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="prg_DriePompen" Id="{54afbad6-5034-4df3-8f9f-7a6d22205edd}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM prg_DriePompen
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="prg_DriePompen">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>