<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.12">
  <POU Name="prg_Finale" Id="{64dd82a2-8bfc-427e-8cbc-e39c4323b1b5}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM prg_Finale
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="prg_Finale">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>