<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="prg_SearchString" Id="{f413e5f4-2f33-48b8-97e6-0d917fead22f}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM prg_SearchString
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="prg_SearchString">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>