<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="prg_Personeelsdata" Id="{e915f581-d964-4e15-9a7a-844beb749528}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM prg_Personeelsdata
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="prg_Personeelsdata">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>