<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="prg_GetMinimum" Id="{15009af4-906b-4550-a345-9c273a7df78c}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM prg_GetMinimum
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="prg_GetMinimum">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>