<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="prg_Checker_Functions" Id="{66c95a9d-9eaf-4575-9bcd-5372ab762b71}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM prg_Checker_Functions
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="prg_Checker_Functions">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>