<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="prg_PWM" Id="{cb594440-59ea-46ee-beb4-c1d9f1bc6c1a}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM prg_PWM
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="prg_PWM">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>