<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="MAIN" Id="{ca3d6acd-d237-42df-a5f8-441aa260ece2}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//prg_Teleruptor();
//prg_Startveiligheid();
//prg_TrappenhuisautomaatVerlenging();
//prg_TrappenhuisautomaatTijdsinstelling();
//prg_Knipperlicht();
//prg_Millis();
//prg_OpenbaarToilet();
prg_AutomatischeDeur();
prg_Setpointsturing();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="7" Count="5" />
      <LineId Id="16" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>