<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="prg_DraaiRichtingMotor" Id="{52597bfd-aa8a-4647-945c-0d4f5bed4876}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM prg_DraaiRichtingMotor
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="prg_DraaiRichtingMotor">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>