<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="prg_TrappenhuisautomaatVerlenging" Id="{d8cffbf9-f8ac-4eaf-9142-3cf7ed2e24a6}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM prg_TrappenhuisautomaatVerlenging
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="prg_TrappenhuisautomaatVerlenging">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>