<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="prg_ProductenTellen" Id="{e18161f0-894e-406c-a80f-4b6353825cb2}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM prg_ProductenTellen
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="prg_ProductenTellen">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>