<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="prg_Parking" Id="{9366d75b-1989-4a9f-95de-b8db72f8ada3}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM prg_Parking
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="prg_Parking">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>