<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="prg_Startveiligheid" Id="{7fb4313d-8469-4bcf-a12c-766c3eece71d}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM prg_Startveiligheid
VAR
	bStart			AT		%I*		:BOOL;
	
	bMachine		AT		%Q*		:BOOL;
	fbStart: TON;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbStart(IN:= bStart, PT:= T#5S, Q=> bMachine);]]></ST>
    </Implementation>
    <LineIds Name="prg_Startveiligheid">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>