<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="prg_Belsignaal" Id="{d7551642-c751-4d8c-9494-27556209977f}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM prg_Belsignaal
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="prg_Belsignaal">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>