<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="prg_Millis" Id="{dd5a5dd1-f5f8-4920-a311-12fff34722f3}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM prg_Millis
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="prg_Millis">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>