<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="prg_Teleruptor" Id="{81aa6041-588d-4d22-ae97-814c8e821228}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM prg_Teleruptor
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="prg_Teleruptor">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>